
src_main_dir: /srv/dev/data/

DATASET_TAG: customer

test: test

#typ_store: informix
#typ_store: sqlite
typ_store: mysql


db:
    dbname: xmlflattest
    dbuser: test
    dbpass: test

    tablename : kunden
    keyname   : coid




