
src_main_dir: /path/to/sources
src_pattern:  'filename_prefix_.*\.xml'

DATASET_TAG: customer

test: test

typ_store: informix
#typ_store: sqlite

db:
    dbname: 
    dbuser: 
    dbpass: 


    tablename : kunden
    keyname   : coid




